<script>
    // err错误类型
    // 1.
    // ReferenceError
    // console.log(a);
    // (引用错误,没有捕获error,下面的代码不会执行)
    // 2.
    // TypeError
    // console.log(a.xxx);
    // (属性错误,不存在该属性)
    // 3.
    // RangeError
    // function fn(){
    //     fn()
    // }
    // fn()
    // (范围限制,这是一个递归调用,函数内部调用自己是一个调用限制(层次))
    // 4.
    // SyntaxError
    // 语法错误

setTimeout(()=>{
    console.log("0")
},0)
new Promise((resolve,reject)=>{
    console.log("1")
    resolve()
}).then(()=>{
    console.log("2")
    new Promise((resolve,reject)=>{
        console.log("3")
        resolve()
    }).then(()=>{
        console.log("4");
    }).then(()=>{
        console.log("5");
    })
}).then(()=>{
    console.log("6");
})

new Promise((resolve,reject)=>{
    console.log("7");
    resolve()
}).then(()=>{
    console.log("8");
})
</script>